import type { CatalogProduct } from '../../core/models/marketplace.models';

export const MARKETPLACE_PRODUCTS: readonly CatalogProduct[] = [
  {
    sku: 'founder-potion-pack',
    name: 'Pacote de Poções Founder',
    category: 'consumable',
    typeLabel: 'Consumível premium',
    description: 'Acelera farm, quests e progressão inicial com poções utilitárias prontas para uso.',
    shortDescription: 'Kit de suporte para evoluir mais rápido logo após a confirmação do pagamento.',
    icon: '🧪',
    supportedRealms: ['main-world'],
    realmLabel: 'Exclusivo para main-world',
    deliveryLabel: 'Entrega automática no inventário',
    priceInBrl: 19.9,
    tags: ['starter', 'farm rápido', 'progressão'],
    supportsQuantity: true,
    minQuantity: 1,
    maxQuantity: 5,
    deliveryMode: 'mock_auto_delivered',
  },
  {
    sku: 'aurora-blade-skin',
    name: 'Skin Aurora Blade',
    category: 'weapon-skin',
    typeLabel: 'Skin de arma',
    description: 'Visual raro para espada com aplicação cosmética imediata e destaque em combate.',
    shortDescription: 'Skin premium para deixar o personagem mais marcante em batalhas e eventos.',
    icon: '🗡️',
    supportedRealms: ['main-world'],
    realmLabel: 'Exclusivo para main-world',
    deliveryLabel: 'Entrega automática cosmética',
    priceInBrl: 29.9,
    tags: ['visual raro', 'popular', 'cosmético'],
    supportsQuantity: false,
    minQuantity: 1,
    maxQuantity: 1,
    deliveryMode: 'mock_auto_delivered',
  },
  {
    sku: 'shadow-striker-set',
    name: 'Set Shadow Striker',
    category: 'character-skin',
    typeLabel: 'Skin de personagem',
    description: 'Conjunto sazonal com presença forte no PvP e aplicação direta no personagem informado.',
    shortDescription: 'Skin completa para destacar o personagem no seasonal-world com visual exclusivo.',
    icon: '🥷',
    supportedRealms: ['seasonal-world'],
    realmLabel: 'Exclusivo para seasonal-world',
    deliveryLabel: 'Entrega automática ao personagem',
    priceInBrl: 34.9,
    tags: ['seasonal', 'edição limitada', 'pvp'],
    supportsQuantity: false,
    minQuantity: 1,
    maxQuantity: 1,
    deliveryMode: 'mock_auto_delivered',
  },
  {
    sku: 'ember-fox-pet',
    name: 'Pet Ember Fox',
    category: 'pet',
    typeLabel: 'Pet premium',
    description: 'Companion exclusivo para acompanhar o personagem e reforçar status dentro do jogo.',
    shortDescription: 'Pet raro para quem quer presença visual e companhia fixa durante a jornada.',
    icon: '🦊',
    supportedRealms: ['main-world'],
    realmLabel: 'Exclusivo para main-world',
    deliveryLabel: 'Entrega automática do companion',
    priceInBrl: 39.9,
    tags: ['pet raro', 'vip', 'companheiro'],
    supportsQuantity: false,
    minQuantity: 1,
    maxQuantity: 1,
    deliveryMode: 'mock_auto_delivered',
  },
  {
    sku: 'war-chest-bundle',
    name: 'Bundle War Chest',
    category: 'bundle',
    typeLabel: 'Bundle de guerra',
    description: 'Pacote de alto valor com moedas, consumíveis e bônus visuais para clãs e eventos.',
    shortDescription: 'Bundle completo para acelerar progressão e preparar personagens em múltiplos realms.',
    icon: '🎁',
    supportedRealms: ['main-world', 'seasonal-world', 'test-world'],
    realmLabel: 'Compatível com main-world, seasonal-world e test-world',
    deliveryLabel: 'Entrega em lote após confirmação',
    priceInBrl: 49.9,
    tags: ['bundle', 'evento', 'multi-realm'],
    supportsQuantity: true,
    minQuantity: 1,
    maxQuantity: 3,
    deliveryMode: 'backend_pending',
  },
];

export const MARKETPLACE_REALMS = ['main-world', 'seasonal-world', 'test-world'] as const;
