worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    sendfile on;
    keepalive_timeout 65;

    upstream scalable_client {
        server client:9000;
    }

    upstream scalable_hub_api {
        server hub:9526;
    }

    upstream scalable_hub_ws {
        server hub:9527;
    }

    server {
        listen 80;
        server_name localhost;

        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Ssl $http_x_forwarded_ssl;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;

        location = /server {
            proxy_pass http://scalable_hub_api;
        }

        location = /all {
            proxy_pass http://scalable_hub_api;
        }

        location = /leaderboards {
            proxy_pass http://scalable_hub_api;
        }

        location = /isOnline {
            proxy_pass http://scalable_hub_api;
        }

        location /api/ {
            proxy_pass http://scalable_hub_api;
        }

        location /ws {
            proxy_pass http://scalable_hub_ws;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_read_timeout 300s;
        }

        location /hub/ws {
            proxy_pass http://scalable_hub_ws;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_read_timeout 300s;
        }

        location / {
            proxy_pass http://scalable_client;
            proxy_http_version 1.1;
        }
    }
}
