services:
    client-server:
        build:
            context: ../
            dockerfile: docker/Dockerfile
        env_file:
            - ../.env
        networks:
            - internos
        volumes:
            - ../:/app
            - /app/node_modules
        expose:
            - '9000'
            - '9001'
            - '9526'
            - '9527'
            - '9528'
        depends_on:
            - mongo
        command: >
            /bin/sh -c "yarn install && yarn build &&
            (
                yarn workspace @kaetram/server start --host 0.0.0.0 --port 9001 &
                yarn workspace @kaetram/hub start &
                HOST=0.0.0.0 PORT=9000 yarn workspace @kaetram/client start &
                wait
            )"

    nginx:
        image: nginx:alpine
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        ports:
            - '81:80'
        depends_on:
            - client-server
        networks:
            - internos

    mongo:
        image: mongo:6.0
        restart: unless-stopped
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        volumes:
            - mongo_data:/data/db
        networks:
            - internos

volumes:
    mongo_data:

networks:
    internos:
        external: true
