name: acacia-multiworld-scalable-base

services:
    hub:
        build:
            context: ..
            dockerfile: docker-multiworld-scalable/hub/Dockerfile
        env_file:
            - ./hub/.env
        volumes:
            - ./hub/.env:/app/.env:ro
        command: yarn workspace @acacia/hub start
        expose:
            - '9526'
            - '9527'
            - '9528'
        ports:
            - '9526:9526'
            - '9527:9527'
            - '9528:9528'
        networks:
            - scalable

    client:
        build:
            context: ..
            dockerfile: docker-multiworld-scalable/client/Dockerfile
        env_file:
            - ./client/.env
        volumes:
            - ./client/.env:/app/.env:ro
        command: yarn workspace @acacia/client start --host 0.0.0.0 --port 9000
        expose:
            - '9000'
        depends_on:
            - hub
        networks:
            - scalable

networks:
    scalable:
        name: acacia-scalable-runtime
